language: python
python:
  - 3.7
dist: xenial
sudo: false
cache: pip
before_install:
  - python3 --version
install:
  - python3.7 -m pip install pipenv
  - pipenv install --dev
script:
  - flake8
  - pytest -v
